CREATE TABLE IF NOT EXISTS `societies` (
  `society_id` INT(11) NOT NULL AUTO_INCREMENT,
  `society_unique_id` VARCHAR(50) NOT NULL,
  `society_legal_name` TEXT NOT NULL,
  `society_reg_number` VARCHAR(255) NOT NULL,
  `society_reg_date` DATE NOT NULL,
  `society_address1` TEXT NOT NULL,
  `society_address2` TEXT DEFAULT NULL,
  `society_landmark` TEXT DEFAULT NULL,
  `society_country` VARCHAR(255) NOT NULL,
  `society_state` VARCHAR(255) NOT NULL,
  `society_city` VARCHAR(255) NOT NULL,
  `society_pincode` VARCHAR(10) NOT NULL,
  `society_primary_contact_fullname` VARCHAR(255) NOT NULL,
  `society_primary_contact_designation` VARCHAR(255) NOT NULL,
  `society_authorised_phone_number` VARCHAR(20) NOT NULL,
  `society_authorised_email_address` VARCHAR(255) NOT NULL,
  `society_number_of_units` INT(11) NOT NULL,
  `society_number_of_blocks_wings` INT(11) NOT NULL,
  `society_type` ENUM('residential', 'commercial', 'both') NOT NULL DEFAULT 'residential',
  `society_occupancy_status` ENUM('ready_to_move', 'under_construction', 'partially_occupied', 'fully_occupied') NOT NULL DEFAULT 'ready_to_move',
  `society_rera_registration_id` VARCHAR(50) DEFAULT NULL,
  `society_pan` VARCHAR(15) NOT NULL,
  `society_last_audit_year` YEAR(4) NOT NULL,
  `society_financial_cycle_start` VARCHAR(10) NOT NULL,
  `society_financial_cycle_end` VARCHAR(10) NOT NULL,
  `society_domain` VARCHAR(255) DEFAULT NULL,
  `society_status` ENUM('pending_verification', 'active', 'inactive', 'suspended') NOT NULL DEFAULT 'pending_verification',
  `society_added_by` VARCHAR(50) NOT NULL,
  `society_added_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `society_updated_on` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`society_id`),
  UNIQUE KEY `society_unique_id` (`society_unique_id`),
  UNIQUE KEY `society_reg_number` (`society_reg_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
